from .produto import get_produto, get_produtos, create_produto, update_produto
from .cliente import get_cliente, get_clientes, create_cliente
from .cliente_telefone import get_cliente_telefone, get_clientes_telefone, create_cliente_telefone, get_cliente_telefones
from .cliente_email import get_cliente_email, get_clientes_email, create_cliente_email, get_cliente_emails
from .transportadora import get_transportadora, get_transportadoras, create_transportadora
from .transportadora_email import get_transportadora_email, get_transportadora_emails, get_transportadoras_email , create_transportadora_email
from .transportadora_telefone import get_transportadora_telefone, get_transportadora_telefones, get_transportadoras_telefone , create_transportadora_telefone